services:
  - type: web
    name: digross-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
